4. LAPTOP VS MOBILE VIEWERSHIP

-------

SELECT SUM(CASE WHEN DEVICE_TYPE='laptop' THEN 1 ELSE 0 END) 
AS LAPTOP_VIEWS,
SUM(CASE WHEN DEVICE_TYPE IN('phone','tablet')THEN 1 ELSE 0 END)
AS MOBILE_VIEWS FROM VIEWERSHIP;